name: Publish to mod.io

on:
  workflow_dispatch:
    inputs:
      mod_version:
        type: string
        description: Mod version
        required: true

jobs:
  create_modio_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Find and Replace MOD_VERSION_PLACEHOLDER
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "MOD_VERSION_PLACEHOLDER"
          replace: ${{ github.event.inputs.mod_version }}
          regex: false
        
      - name: Build Mod
        run: dotnet build --no-restore --configuration RELEASE -p:Version=${{ github.event.inputs.mod_version }}
        
      - name: Create ModFolder folder
        run: mkdir ModIoPackage
        
      - name: Copy Mod
        run: cp ./DraggableUtils/bin/Release/netstandard2.1/DraggableUtils.dll ModIoPackage
        
      - name: Copy Everything to modIO package
        run: cp -r ./DraggableUtils/package/. ModIoPackage
        
      - name: Remove mod.json
        run: rm ModIoPackage/mod.json
        
      - name: Rename mod.ci.json to mod.json
        run: mv ModIoPackage/mod.ci.json ModIoPackage/mod.json
        
      - name: Upload mod to Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: DraggableUtils_${{ github.event.inputs.mod_version }}
          path: ModIoPackage
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: DraggableUtils_${{ github.event.inputs.mod_version }}.zip
          path: "./"
          directory: ModIoPackage
          
      - name: Test
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Test
          path: ModIoPackage/DraggableUtils_${{ github.event.inputs.mod_version }}.zip
          
      - uses: nickelc/upload-to-modio@v2.0.0
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: 3659
          mod: 2669290
          version: ${{ github.event.inputs.mod_version }}
          path: ModIoPackage/DraggableUtils_${{ github.event.inputs.mod_version }}.zip
          active: true
          changelog: "-"